import datetime
import smtplib

quotes = [
    "Life becomes clearer when you stop rushing and start noticing.",
    "Small steps still move you forward.",
    "Your ordinary days are quietly becoming your life story.",
    "Peace often begins where comparison ends.",
    "Do what you can with what you have today.",
    "Every morning gives you another chance to begin.",
    "A meaningful life is built from meaningful moments.",
    "Progress does not need to be loud to be real.",
    "Protect your time; it is part of your life.",
    "Some chapters hurt, but they still move the story forward.",
    "Be patient with the person you are becoming.",
    "Kindness costs little and can change someone's entire day.",
    "Your future is shaped by what you repeatedly do today.",
    "Not every delay is a denial; sometimes it is preparation.",
    "Enjoy the journey while you are building the destination.",
    "Let yesterday teach you, not control you.",
    "Courage often looks like taking one more step.",
    "A calm mind can find possibilities inside difficult days.",
    "You do not need a perfect day to have a good day.",
    "Choose people who make your life feel more honest.",
    "Gratitude turns what is present into something precious.",
    "Rest is not quitting; it is part of continuing.",
    "Your mistakes are teachers when you are willing to listen.",
    "Life gets lighter when you stop carrying what is not yours.",
    "Make room for joy, even on busy days.",
    "The best time to appreciate someone is while they are here.",
    "Your worth is not measured by your productivity.",
    "Sometimes the bravest choice is to begin again.",
    "Good things often grow quietly before anyone notices.",
    "Be where your feet are; this moment is your life.",
    "Dreams need patience as much as they need ambition.",
    "You cannot control every event, but you can choose your response.",
    "Keep learning; curiosity keeps life young.",
    "A simple life can still be a deeply successful life.",
    "Do not let one difficult day define your whole journey.",
    "Your attention is valuable; spend it carefully.",
    "Give yourself permission to grow at your own pace.",
    "Hope is a small light that can survive a long night.",
    "Listen more closely to the people you love.",
    "Success feels different when you have someone to share it with.",
    "Life is made richer by the memories we create, not the things we collect.",
    "Every ending creates space for something new.",
    "Be proud of how far you have come, even if you are not finished.",
    "Consistency can accomplish what motivation cannot sustain.",
    "A peaceful heart is a quiet kind of wealth.",
    "Do not postpone happiness until everything is perfect.",
    "Your story does not need to look like anyone else's.",
    "Choose progress over perfection.",
    "Sometimes changing direction is part of moving forward.",
    "Good friendships are built one honest conversation at a time.",
    "The smallest act of kindness can become someone's brightest memory.",
    "Life rewards attention; notice the little things.",
    "Your mind needs rest just as your body does.",
    "Learn to say no to what drains you.",
    "One thoughtful decision can change the direction of a year.",
    "Be gentle with people; you rarely know what they are carrying.",
    "Your habits become the architecture of your days.",
    "Do not confuse being busy with being alive.",
    "Celebrate small victories; they are evidence of movement.",
    "A difficult season does not last forever.",
    "Sometimes clarity arrives after you stop forcing an answer.",
    "Make time for the people who make time for you.",
    "Life is too valuable to spend entirely in the future.",
    "Your character is built when nobody is watching.",
    "Keep your promises to yourself.",
    "Joy can be found in ordinary places when you look closely.",
    "Every skill begins with being willing to be a beginner.",
    "Failure is information when you choose to learn from it.",
    "Your past explains you; it does not have to imprison you.",
    "Take the next right step, even when the whole path is hidden.",
    "Kind words can stay with someone for years.",
    "Do not underestimate what a peaceful evening can repair.",
    "Life becomes richer when you make room for wonder.",
    "Be thankful for people who tell you the truth with kindness.",
    "Your best days may still be ahead of you.",
    "Keep going, but remember to enjoy what you have already built.",
    "Confidence grows when you keep showing up.",
    "Some answers arrive only after enough time has passed.",
    "Your attention shapes your experience of life.",
    "Choose memories over unnecessary possessions.",
    "Love is often expressed through small, consistent actions.",
    "Do not wait for a milestone to celebrate being alive.",
    "Every person you meet can teach you something.",
    "Patience is strength that knows how to wait.",
    "Your life does not need an audience to have meaning.",
    "Make decisions your future self will thank you for.",
    "Peace is sometimes found by releasing the need to be right.",
    "Keep your heart open without abandoning your boundaries.",
    "Hard work matters, but so does knowing when to rest.",
    "One good conversation can change an entire week.",
    "Life is a collection of moments; treat them as valuable.",
    "Do not let fear make every decision for you.",
    "Your direction matters more than your speed.",
    "Learn from criticism without letting it define you.",
    "A grateful mind notices abundance where others see ordinary things.",
    "Give people flowers while they can still smell them.",
    "Your presence can be more valuable than your advice.",
    "Do not rush through a season simply because it is difficult.",
    "Every sunrise is proof that beginnings can return.",
    "Choose simplicity when complexity adds nothing.",
    "Your relationships deserve the same attention as your ambitions.",
    "Be curious about people instead of quickly judging them.",
    "A healthy boundary is an act of respect, not rejection.",
    "Sometimes the most productive thing you can do is breathe.",
    "Life becomes beautiful when you stop waiting for permission to enjoy it.",
    "Keep learning from the people and places around you.",
    "Your effort counts even when the result is not immediate.",
    "Do not measure your life only by what you achieved.",
    "The people you love will remember how you made them feel.",
    "Make peace with the fact that you cannot please everyone.",
    "A quiet life can hold extraordinary meaning.",
    "Your choices become easier when your values are clear.",
    "Protect your mornings from unnecessary noise.",
    "Be the reason someone feels a little less alone today.",
    "Do not mistake uncertainty for failure.",
    "Some roads become visible only after you start walking.",
    "Your life can change through one small decision repeated consistently.",
    "Appreciate the people who celebrate your growth without competing with it.",
    "Let curiosity be stronger than fear.",
    "Sometimes healing looks like simply having a normal day again.",
    "Your future needs your attention more than your regrets do.",
    "Take pictures, but also put the camera down and live the moment.",
    "Be willing to change your mind when you learn something new.",
    "Life is not a race against other people's timelines.",
    "Make space for hobbies that have no purpose except joy.",
    "A sincere apology can repair what pride would leave broken.",
    "Do not save all your happiness for later.",
    "Your home should be a place where your mind can breathe.",
    "Remember that everyone is learning how to live for the first time.",
    "Small acts repeated daily can create extraordinary change.",
    "Your values are revealed by what you make time for.",
    "Be proud of quiet progress.",
    "Sometimes letting go is how you make room to receive.",
    "Do not let temporary emotions make permanent decisions.",
    "A good life contains both ambition and contentment.",
    "Listen to your loved ones before the moment passes.",
    "Your life is happening now, not after the next achievement.",
    "Choose understanding before judgment.",
    "Do not be ashamed of starting over.",
    "The best memories are often made without a plan.",
    "Give yourself the same patience you give to others.",
    "Your mistakes do not cancel your progress.",
    "Keep people close who make honesty feel safe.",
    "Life teaches through repetition; pay attention to the lesson.",
    "A little discipline today can create a lot of freedom tomorrow.",
    "Be careful what you normalize in your life.",
    "Sometimes you need distance to understand what truly matters.",
    "Your energy is limited; spend it on what matters.",
    "Do not let a bad chapter convince you the whole book is bad.",
    "Make room for laughter.",
    "Your life needs pauses, not just destinations.",
    "Kindness is never wasted, even when it goes unnoticed.",
    "Stay humble when things go well and hopeful when they do not.",
    "Your perspective can turn a setback into a lesson.",
    "Be present enough to notice when life is being good to you.",
    "Not everything needs to be fixed today.",
    "Give yourself credit for surviving days you thought you could not.",
    "Your dreams deserve action, not just admiration.",
    "Life becomes easier when you focus on what you can influence.",
    "Do not let perfection steal the pleasure of progress.",
    "Ask for help when you need it; strength is not isolation.",
    "Make your words something people feel safe carrying home.",
    "Every relationship grows through attention.",
    "Choose experiences that make stories, not just expenses.",
    "Your body deserves care, not punishment.",
    "Sometimes the strongest answer is a calm one.",
    "Keep your promises, especially the small ones.",
    "Do not confuse familiarity with happiness.",
    "A grateful heart has a longer memory for good things.",
    "Your life can be meaningful without being impressive.",
    "Learn to enjoy your own company.",
    "Take responsibility for your choices without being cruel to yourself.",
    "Good things become better when they are shared.",
    "Do not allow one person's opinion to become your identity.",
    "Life changes when your priorities become clearer.",
    "Give yourself permission to outgrow old versions of yourself.",
    "Your attention is a form of love.",
    "Some opportunities arrive disguised as uncomfortable beginnings.",
    "Be patient with slow seasons.",
    "Your next chapter can be different from your last.",
    "Do not wait until you are exhausted to value rest.",
    "A thoughtful life is built one decision at a time.",
    "Keep your standards high and your heart soft.",
    "Life is easier to appreciate when you stop taking ordinary blessings for granted.",
    "Your kindness may be remembered long after your words are forgotten.",
    "Make today useful, but also make it yours.",
    "Do not let yesterday borrow too much from today.",
    "Every challenge can teach you something about yourself.",
    "Be honest about what you want and gentle about how you pursue it.",
    "Your peace is worth protecting.",
    "Sometimes the answer is simply to keep going.",
    "Celebrate people while they are still part of your everyday life.",
    "A meaningful life is rarely built by accident.",
    "Your habits quietly vote for the person you become.",
    "Choose courage over comfort when the moment calls for it.",
    "Life does not owe us certainty; we can still choose hope.",
    "Let your actions speak louder than your intentions.",
    "Do not compare your beginning with someone else's middle.",
    "Make time for people who make ordinary days memorable.",
    "Forgive yourself for not knowing then what you know now.",
    "Your future is not required to repeat your past.",
    "Take care of the relationships that money cannot replace.",
    "Sometimes slowing down helps you see what speed was hiding.",
    "Your life deserves more than constant distraction.",
    "Keep a little room in your day for the unexpected.",
    "Be thankful for lessons that arrived disguised as difficulties.",
    "Growth often feels uncomfortable because it asks you to become unfamiliar.",
    "Do not let fear turn every possibility into a problem.",
    "Choose conversations over assumptions.",
    "Your loved ones need your presence more than your perfection.",
    "Make room for people who bring peace, not confusion.",
    "Your journey can be meaningful even when nobody applauds it.",
    "Small kindness is still kindness.",
    "Do not underestimate the power of a fresh start.",
    "Your best investment is often in your own character.",
    "Life is easier when you stop arguing with what has already happened.",
    "Take responsibility for today without carrying all of tomorrow.",
    "Your words can build bridges or walls; choose carefully.",
    "Be willing to learn from someone younger than you.",
    "Sometimes happiness is simply noticing that nothing is wrong.",
    "Your life is more than your job title.",
    "Make decisions based on values, not temporary applause.",
    "Rest before resentment tells you that you needed it.",
    "Do not let disappointment erase gratitude.",
    "Your confidence grows every time you keep a promise to yourself.",
    "Give yourself permission to enjoy simple things.",
    "Some friendships are seasons; appreciate them without forcing them to last forever.",
    "Life becomes meaningful through connection, contribution, and growth.",
    "Be patient with people who are still learning how to love well.",
    "Your boundaries teach others how to treat your time.",
    "Do not chase every opportunity; choose the ones that fit your values.",
    "A peaceful mind is built through many small choices.",
    "Keep your sense of humor; life needs it.",
    "Your life can hold both sadness and gratitude at the same time.",
    "Do not postpone a kind word.",
    "Sometimes a walk can solve what sitting still could not.",
    "Be more interested in becoming than appearing.",
    "Your character matters most when circumstances become difficult.",
    "Learn to recognize when enough is enough.",
    "Life is not measured only in years, but in moments fully lived.",
    "Do not let your phone become louder than the people beside you.",
    "Choose depth over constant distraction.",
    "Your future self is listening to what you do today.",
    "Be grateful for the people who stayed when things were difficult.",
    "One honest conversation can prevent a hundred assumptions.",
    "Do not let temporary failure become a permanent identity.",
    "Your life deserves goals that excite you and values that steady you.",
    "Keep some dreams private until they have roots.",
    "Sometimes the most beautiful progress is invisible.",
    "Give yourself time to understand what you truly want.",
    "Your life changes when you change what you repeatedly tolerate.",
    "Be kind without expecting recognition.",
    "Do not confuse being needed with being valued.",
    "Your attention is one of the greatest gifts you can give someone.",
    "Let your failures make you wiser, not smaller.",
    "Choose people who can celebrate your success without feeling threatened.",
    "Life is full of unfinished stories; you do not need every answer today.",
    "Make room for gratitude before asking for more.",
    "Your peace should not depend entirely on circumstances.",
    "Keep moving toward what matters, even slowly.",
    "Sometimes the right path is the one that teaches you the most.",
    "Do not be afraid of quiet periods; growth can happen there.",
    "Your life becomes richer when you notice other people's victories too.",
    "Give more encouragement than criticism.",
    "Every day is an opportunity to practice being the person you want to become.",
    "Do not let one mistake make you forget a hundred good choices.",
    "Your story is still being written.",
    "Choose patience when impatience will only create more work.",
    "Be present for the moments you will someday miss.",
    "Your relationships are living things; they need care.",
    "Do not wait for a crisis to appreciate peace.",
    "Life becomes less complicated when you know what you can let go of.",
    "Your courage can be quiet and still be courage.",
    "Learn to enjoy progress before the finish line.",
    "Make your life spacious enough for both ambition and rest.",
    "Do not let other people's timelines rush your journey.",
    "Your values are a compass when circumstances are confusing.",
    "Be generous with credit and careful with blame.",
    "Sometimes you need to close a door without hating the room behind it.",
    "Life can surprise you after you thought the story was settled.",
    "Keep choosing what brings you closer to the person you respect.",
    "Your mistakes are part of your education.",
    "Do not wait to feel ready; readiness often follows action.",
    "A good life is not a perfect life.",
    "Be grateful for ordinary mornings.",
    "Let your curiosity keep opening doors.",
    "Your mind becomes stronger when you question your assumptions.",
    "Make peace with being misunderstood sometimes.",
    "Do not sacrifice every present moment for a future that is not guaranteed.",
    "Your life deserves attention, not just achievement.",
    "Keep people close who can laugh with you and sit quietly with you.",
    "Sometimes the smallest change creates the biggest relief.",
    "Your past can be a teacher without being your landlord.",
    "Choose actions that your future self will recognize as wise.",
    "Life is too short to make every disagreement a battle.",
    "Protect your ability to be amazed.",
    "Do not forget to celebrate the people who helped you along the way.",
    "Your dreams may change; that does not make them failures.",
    "Be willing to take a different route when the old one no longer fits.",
    "Your life can be both work in progress and something worth celebrating.",
    "Listen when your life is asking you to slow down.",
    "Give yourself permission to be happy without explaining why.",
    "Do not let guilt keep you in places you have outgrown.",
    "Every day offers something worth noticing.",
    "Your kindness can travel farther than you will ever know.",
    "Choose long-term peace over short-term approval.",
    "Sometimes the strongest boundary is simply walking away.",
    "Keep learning, because life keeps changing.",
    "Your effort matters even when nobody sees it.",
    "Do not make permanent judgments from temporary circumstances.",
    "Be grateful for the chance to try again.",
    "Life becomes more beautiful when you stop demanding that it be predictable.",
    "Your best memories may come from days that seemed ordinary at the time.",
    "Give people the benefit of context before giving them a judgment.",
    "Do not let ambition make you forget affection.",
    "Your life needs both roots and room to grow.",
    "Choose progress that you can sustain.",
    "Sometimes acceptance is more powerful than resistance.",
    "Your happiness does not need everyone else's approval.",
    "Be the friend you hope to have.",
    "Do not underestimate what one year of consistency can accomplish.",
    "Your life is shaped by what you practice, not just what you wish.",
    "Make time for silence; it can reveal what noise hides.",
    "Every difficult conversation can be an opportunity for greater understanding.",
    "Keep your heart grateful even while your goals remain ambitious.",
    "Do not confuse a slow journey with a wrong journey.",
    "Your future is built in ordinary moments.",
    "Be proud of choosing peace when conflict would have been easier.",
    "Life gives us chances to begin again more often than we notice.",
    "Let people know they matter while you have the chance.",
    "Your values become real when they cost you something.",
    "Do not let one closed door make you stop looking for another.",
    "Take care of today; tomorrow will arrive soon enough.",
    "Sometimes the best plan is simply to keep your priorities clear.",
    "Your life is worth enjoying before everything is figured out.",
    "Be brave enough to admit when you need a change.",
    "Good things take time, and meaningful things often take longer.",
    "Do not make your life smaller to make someone else comfortable.",
    "Your peace is more valuable than winning every argument.",
    "Choose honesty that is kind, not honesty that is cruel.",
    "Life is easier to navigate when you know what matters most.",
    "Keep going through the days when progress feels invisible.",
    "Your presence can be a gift even when you have nothing to say.",
    "Do not wait for perfect circumstances to practice gratitude.",
    "Every person has a story you cannot see.",
    "Be slow to judge and quick to understand.",
    "Your life can change without a dramatic moment; habits can do it quietly.",
    "Make your home a place that restores you.",
    "Do not let success make you forget who helped you begin.",
    "Sometimes peace looks like choosing not to respond.",
    "Your dreams need deadlines, but your life also needs breathing room.",
    "Be thankful for second chances.",
    "Do not confuse a setback with a sentence.",
    "Your life is not behind schedule.",
    "Keep your curiosity alive even when you think you know the answer.",
    "Make room for people who inspire you to become kinder.",
    "Your attention can turn an ordinary moment into a memory.",
    "Choose courage one small decision at a time.",
    "Life can be difficult and beautiful in the same week.",
    "Do not wait for someone else to give you permission to begin.",
    "Your future deserves more focus than your past deserves regret.",
    "Be intentional with the people you love.",
    "Sometimes letting go is an act of trust in what comes next.",
    "Your character is your quiet legacy.",
    "Keep building, even when the progress is measured in inches."
]

today = datetime.datetime.now().date()
start_date = datetime.date(2026,9,27)
difference = today - start_date
quote_number = difference.days%len(quotes)
quote_of_the_day = quotes[quote_number]

my_email = ""
password = ""

with smtplib.SMTP("smtp.gmail.com",port=587) as connection:
    connection.starttls()
    connection.login(user=my_email,password=password)
    connection.sendmail(from_addr=my_email,to_addrs="jesuisnavya@gmail.com",msg=f"Subject:Your Daily Gyan by Sri Sri Rohit Anand Swami ! \n\n {quote_of_the_day}")

